### ISSUE TITLE
fail to load kana-encoded recording list

### ISSUE THREAD

**Issue by vocatart** [team-aie/app#3]
aie fails to load any recording list that is encoded with kana characters. aie will correctly parse any romaji reclist, but fails to parse the same reclist that is kana encoded.

aie produces the following error : 
![image](https://user-images.githubusercontent.com/22067912/81133963-7564a400-8f10-11ea-9d91-b24e61489856.png)

looking at the reclist, there are no duplicate lines. i have attached the kana and romaji reclists
[dieselcvvc_hiragana.txt](https://github.com/team-aie/app/files/4584621/dieselcvvc_hiragana.txt)
[dieselcvvc_romaji.txt](https://github.com/team-aie/app/files/4584622/dieselcvvc_romaji.txt)

**Comment by iluminar-yi** [comment]
It's probably because I rushed through the prototype code, but will take a look!

**Comment by iluminar-yi** [comment]
Okay... So it is an encoding issue. My code assumes all text files are using UTF-8 encoding, which of course isn't always the case. The quick workaround for you as to use this file that I converted. Let me know if that helped (v0.2.0 UI is broken on the recording screen, so consider turning off Internet before you try this).
[dieselcvvc_hiragana_UTF-8.txt](https://github.com/team-aie/app/files/4592876/dieselcvvc_hiragana_UTF-8.txt)
I will also look into automatically determining the file encoding, and having these source files will be really helpful for testing.

**Comment by vocatart** [comment]
This seems to have worked. Thank you, I'm very excited to follow the development of aie!!
