### ISSUE TITLE
黑暗模式下语言选择菜单文字没有变成白色

### ISSUE THREAD

**Issue by oxygen-dioxide** [team-aie/app#99]
![image](https://user-images.githubusercontent.com/54425948/110226837-4dc5da00-7f2d-11eb-8a53-1da23c16949b.png)

**Comment by iluminar-yi** [comment]
谢谢反馈！此问题应该会在[v0.11.0](https://github.com/team-aie/app/releases/tag/v0.11.0)里被修复。如果此问题没有解决的话，欢迎随时Reopen这个Issue。
